name: Java CI

# Trigger this workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    # Run this job on both Ubuntu and Windows
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Compile the Java project
    - name: Compile Java code
      run: |
        mkdir build
        javac -d build $(find ./src -name "*.java")

    # Run the Java application
    - name: Run Java Application
      run: |
        java -cp build com.example.Main  # Replace with your main class
